import type { IconType } from "react-icons";
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiGo,
  SiRust,
  SiPhp,
  SiRuby,
  SiSwift,
  SiKotlin,
  SiCplusplus,
  SiSharp,
  SiDart,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiNuxt,
  SiSvelte,
  SiAngular,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiBootstrap,
  SiSass,
  SiRedux,
  SiVite,
  SiWebpack,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSpring,
  SiLaravel,
  SiGraphql,
  SiTrpc,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiMongodb,
  SiRedis,
  SiSupabase,
  SiFirebase,
  SiPrisma,
  SiDocker,
  SiKubernetes,
  SiGooglecloud,
  SiVercel,
  SiNetlify,
  SiCloudflare,
  SiTerraform,
  SiAnsible,
  SiNginx,
  SiLinux,
  SiUbuntu,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGithubactions,
  SiJest,
  SiVitest,
  SiCypress,
  SiStorybook,
  SiFigma,
  SiEslint,
  SiPrettier,
  SiStripe,
  SiWordpress,
  SiFlutter,
  SiAndroid,
  SiApple,
  SiElectron,
  SiSocketdotio,
  SiZod,
  SiJson,
  SiMarkdown,
} from "react-icons/si";

export type TechIconOption = {
  key: string;
  label: string;
  Icon: IconType;
};

export const TECH_ICONS: TechIconOption[] = [
  { key: "javascript", label: "JavaScript", Icon: SiJavascript },
  { key: "typescript", label: "TypeScript", Icon: SiTypescript },
  { key: "python", label: "Python", Icon: SiPython },
  { key: "go", label: "Go", Icon: SiGo },
  { key: "rust", label: "Rust", Icon: SiRust },
  { key: "php", label: "PHP", Icon: SiPhp },
  { key: "ruby", label: "Ruby", Icon: SiRuby },
  { key: "swift", label: "Swift", Icon: SiSwift },
  { key: "kotlin", label: "Kotlin", Icon: SiKotlin },
  { key: "cpp", label: "C++", Icon: SiCplusplus },
  { key: "csharp", label: "C#", Icon: SiSharp },
  { key: "dart", label: "Dart", Icon: SiDart },
  { key: "react", label: "React", Icon: SiReact },
  { key: "nextjs", label: "Next.js", Icon: SiNextdotjs },
  { key: "vuejs", label: "Vue.js", Icon: SiVuedotjs },
  { key: "nuxtjs", label: "Nuxt.js", Icon: SiNuxt },
  { key: "svelte", label: "Svelte", Icon: SiSvelte },
  { key: "angular", label: "Angular", Icon: SiAngular },
  { key: "html5", label: "HTML5", Icon: SiHtml5 },
  { key: "css3", label: "CSS3", Icon: SiCss },
  { key: "tailwindcss", label: "Tailwind CSS", Icon: SiTailwindcss },
  { key: "bootstrap", label: "Bootstrap", Icon: SiBootstrap },
  { key: "sass", label: "Sass", Icon: SiSass },
  { key: "redux", label: "Redux", Icon: SiRedux },
  { key: "vite", label: "Vite", Icon: SiVite },
  { key: "webpack", label: "Webpack", Icon: SiWebpack },
  { key: "nodejs", label: "Node.js", Icon: SiNodedotjs },
  { key: "express", label: "Express", Icon: SiExpress },
  { key: "nestjs", label: "NestJS", Icon: SiNestjs },
  { key: "django", label: "Django", Icon: SiDjango },
  { key: "flask", label: "Flask", Icon: SiFlask },
  { key: "fastapi", label: "FastAPI", Icon: SiFastapi },
  { key: "spring", label: "Spring", Icon: SiSpring },
  { key: "laravel", label: "Laravel", Icon: SiLaravel },
  { key: "graphql", label: "GraphQL", Icon: SiGraphql },
  { key: "trpc", label: "tRPC", Icon: SiTrpc },
  { key: "postgresql", label: "PostgreSQL", Icon: SiPostgresql },
  { key: "mysql", label: "MySQL", Icon: SiMysql },
  { key: "sqlite", label: "SQLite", Icon: SiSqlite },
  { key: "mongodb", label: "MongoDB", Icon: SiMongodb },
  { key: "redis", label: "Redis", Icon: SiRedis },
  { key: "supabase", label: "Supabase", Icon: SiSupabase },
  { key: "firebase", label: "Firebase", Icon: SiFirebase },
  { key: "prisma", label: "Prisma", Icon: SiPrisma },
  { key: "docker", label: "Docker", Icon: SiDocker },
  { key: "kubernetes", label: "Kubernetes", Icon: SiKubernetes },
  { key: "gcp", label: "Google Cloud", Icon: SiGooglecloud },
  { key: "vercel", label: "Vercel", Icon: SiVercel },
  { key: "netlify", label: "Netlify", Icon: SiNetlify },
  { key: "cloudflare", label: "Cloudflare", Icon: SiCloudflare },
  { key: "terraform", label: "Terraform", Icon: SiTerraform },
  { key: "ansible", label: "Ansible", Icon: SiAnsible },
  { key: "nginx", label: "Nginx", Icon: SiNginx },
  { key: "linux", label: "Linux", Icon: SiLinux },
  { key: "ubuntu", label: "Ubuntu", Icon: SiUbuntu },
  { key: "git", label: "Git", Icon: SiGit },
  { key: "github", label: "GitHub", Icon: SiGithub },
  { key: "gitlab", label: "GitLab", Icon: SiGitlab },
  { key: "githubactions", label: "GitHub Actions", Icon: SiGithubactions },
  { key: "jest", label: "Jest", Icon: SiJest },
  { key: "vitest", label: "Vitest", Icon: SiVitest },
  { key: "cypress", label: "Cypress", Icon: SiCypress },
  { key: "storybook", label: "Storybook", Icon: SiStorybook },
  { key: "figma", label: "Figma", Icon: SiFigma },
  { key: "eslint", label: "ESLint", Icon: SiEslint },
  { key: "prettier", label: "Prettier", Icon: SiPrettier },
  { key: "stripe", label: "Stripe", Icon: SiStripe },
  { key: "wordpress", label: "WordPress", Icon: SiWordpress },
  { key: "flutter", label: "Flutter", Icon: SiFlutter },
  { key: "android", label: "Android", Icon: SiAndroid },
  { key: "apple", label: "Apple / iOS", Icon: SiApple },
  { key: "electron", label: "Electron", Icon: SiElectron },
  { key: "socketio", label: "Socket.IO", Icon: SiSocketdotio },
  { key: "zod", label: "Zod", Icon: SiZod },
  { key: "json", label: "JSON", Icon: SiJson },
  { key: "markdown", label: "Markdown", Icon: SiMarkdown },
];

const TECH_ICON_MAP = new Map(TECH_ICONS.map((option) => [option.key, option]));

export function getTechIcon(key: string | undefined): TechIconOption | undefined {
  if (!key) return undefined;
  return TECH_ICON_MAP.get(key);
}
